### ISSUE TITLE
Unable to Access `.name` property in `main.go`

### ISSUE THREAD

**Issue by mdwiltfong** [mdwiltfong/PokeDex#1]
When calling on `.CliCommandMap()` in `main.go`, I am not able to properly access any of the properties of the `cliCommand` struct. 

I could use some help identifying why I can't access this property despite importing it. 

<img width="818" alt="Screenshot 2024-02-10 at 2 47 58 PM" src="https://github.com/mdwiltfong/PokeDex/assets/76107997/defbb759-6461-4739-8a5d-3b2e7d3d530b">

**Comment by tochev** [comment]
You probably need to name the fields with a starting upper case letter (e.g., `Name` , `Description`, `Callback`) as otherwise they will not be accessible from other modules - https://go.dev/ref/spec#Exported_identifiers (the same applies for `CliCommand`).

**Comment by mdwiltfong** [comment]
Thanks @tochev ! That indeed was the problem!
